import type { ReactNode } from "react";
import clsx from "clsx";

export function Card({
  children,
  className,
  as: Tag = "div",
}: {
  children: ReactNode;
  className?: string;
  as?: "div" | "section" | "article";
}) {
  return <Tag className={clsx("panel p-5", className)}>{children}</Tag>;
}

export function SectionTitle({
  title,
  subtitle,
  action,
}: {
  title: string;
  subtitle?: string;
  action?: ReactNode;
}) {
  return (
    <div className="mb-4 flex items-start justify-between gap-4">
      <div>
        <h2 className="text-sm font-semibold uppercase tracking-[0.14em] text-slate-300">{title}</h2>
        {subtitle ? <p className="mt-1 text-sm text-slate-500">{subtitle}</p> : null}
      </div>
      {action}
    </div>
  );
}

export function StatCard({
  label,
  value,
  hint,
  tone = "default",
}: {
  label: string;
  value: string;
  hint?: string;
  tone?: "default" | "critical" | "success" | "accent";
}) {
  const toneClass = {
    default: "text-slate-50",
    critical: "text-signal-critical",
    success: "text-signal-success",
    accent: "text-accent-cyan",
  }[tone];
  return (
    <div className="panel panel-hover p-4">
      <p className="label-caps">{label}</p>
      <p className={clsx("stat-value mt-2", toneClass)}>{value}</p>
      {hint ? <p className="mt-1 text-xs text-slate-500">{hint}</p> : null}
    </div>
  );
}

export function Badge({
  children,
  className,
  title,
}: {
  children: ReactNode;
  className?: string;
  title?: string;
}) {
  return (
    <span
      title={title}
      className={clsx(
        "inline-flex items-center gap-1 rounded-full border px-2 py-0.5 text-[11px] font-medium",
        className ?? "border-slate-500/40 bg-slate-500/10 text-slate-300",
      )}
    >
      {children}
    </span>
  );
}

export function Skeleton({ className }: { className?: string }) {
  return <div className={clsx("animate-pulse rounded-md bg-base-600/60", className)} />;
}

export function EmptyState({ title, description, action }: { title: string; description?: string; action?: ReactNode }) {
  return (
    <div className="flex flex-col items-center justify-center gap-2 rounded-lg border border-dashed border-base-600 py-10 text-center">
      <p className="text-sm font-medium text-slate-300">{title}</p>
      {description ? <p className="max-w-md text-xs text-slate-500">{description}</p> : null}
      {action}
    </div>
  );
}

export function ErrorState({ message, onRetry }: { message: string; onRetry?: () => void }) {
  return (
    <div className="rounded-lg border border-signal-critical/40 bg-signal-critical/10 p-4">
      <p className="text-sm font-medium text-signal-critical">Something went wrong</p>
      <p className="mt-1 text-xs text-slate-300">{message}</p>
      {onRetry ? (
        <button
          type="button"
          onClick={onRetry}
          className="focus-ring mt-3 rounded-md border border-signal-critical/50 px-3 py-1 text-xs font-medium text-signal-critical hover:bg-signal-critical/10"
        >
          Retry
        </button>
      ) : null}
    </div>
  );
}

export function PrototypeSimulationNote({ className }: { className?: string }) {
  return (
    <p className={clsx("text-[11px] leading-relaxed text-slate-500", className)}>
      <span className="font-semibold text-signal-warning">Prototype Simulation.</span> Outcomes shown here are
      generated by the seeded demand model, not measured in the real world.
    </p>
  );
}
