"""initial schema

Revision ID: cfb103bf54c2
Revises: 
Create Date: 2026-09-22 07:39:52.101825
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'cfb103bf54c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=160), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('sku', sa.String(length=32), nullable=False),
    sa.Column('trigger', sa.String(length=64), nullable=False),
    sa.Column('agent', sa.String(length=32), nullable=True),
    sa.Column('decision', sa.String(length=64), nullable=False),
    sa.Column('inputs_summary', sa.JSON(), nullable=False),
    sa.Column('recommendation', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('execution_result', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_occurred_at'), 'audit_logs', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_sku'), 'audit_logs', ['sku'], unique=False)
    op.create_table('b2b_buyers',
    sa.Column('business_name', sa.String(length=160), nullable=False),
    sa.Column('contact_name', sa.String(length=120), nullable=False),
    sa.Column('required_categories', sa.JSON(), nullable=False),
    sa.Column('location_city', sa.String(length=80), nullable=False),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('lon', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('required_quantity', sa.Integer(), nullable=False),
    sa.Column('maximum_budget', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('preferred_unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reliability_score', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('maximum_budget >= 0', name='ck_buyers_budget_non_negative'),
    sa.CheckConstraint('required_quantity > 0', name='ck_buyers_quantity_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_b2b_buyers_business_name'), 'b2b_buyers', ['business_name'], unique=False)
    op.create_table('categories',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('elasticity', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('co_purchase_affinity', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('stores',
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('region', sa.String(length=80), nullable=False),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('lon', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stores_code'), 'stores', ['code'], unique=True)
    op.create_table('products',
    sa.Column('sku', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('list_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('b2b_floor_pct', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('dimensions_cm', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('list_price > 0', name='ck_products_price_positive'),
    sa.CheckConstraint('unit_cost > 0', name='ck_products_cost_positive'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('forecasts',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('predicted_units', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('model_metrics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'store_id', 'as_of', 'horizon_days', name='uq_forecast_key')
    )
    op.create_index(op.f('ix_forecasts_product_id'), 'forecasts', ['product_id'], unique=False)
    op.create_index(op.f('ix_forecasts_store_id'), 'forecasts', ['store_id'], unique=False)
    op.create_table('inventory',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('discount_pct', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('first_received_at', sa.Date(), nullable=False),
    sa.Column('last_sold_at', sa.Date(), nullable=True),
    sa.Column('location_code', sa.String(length=24), nullable=False),
    sa.Column('updated_at', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('discount_pct >= 0 AND discount_pct <= 0.95', name='ck_inventory_discount_range'),
    sa.CheckConstraint('quantity >= 0', name='ck_inventory_quantity_non_negative'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'store_id', name='uq_inventory_product_store')
    )
    op.create_index(op.f('ix_inventory_last_sold_at'), 'inventory', ['last_sold_at'], unique=False)
    op.create_index(op.f('ix_inventory_product_id'), 'inventory', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_store_id'), 'inventory', ['store_id'], unique=False)
    op.create_table('recovery_cases',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('triggers', sa.JSON(), nullable=False),
    sa.Column('age_days', sa.Integer(), nullable=False),
    sa.Column('days_since_sale', sa.Integer(), nullable=False),
    sa.Column('forecast_30d', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('excess_units', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock_units', sa.Integer(), nullable=False),
    sa.Column('capital_locked', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('capital_at_risk', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('risk_band', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_cases_product_id'), 'recovery_cases', ['product_id'], unique=False)
    op.create_index('ix_recovery_cases_product_store', 'recovery_cases', ['product_id', 'store_id'], unique=False)
    op.create_index(op.f('ix_recovery_cases_risk_band'), 'recovery_cases', ['risk_band'], unique=False)
    op.create_index(op.f('ix_recovery_cases_status'), 'recovery_cases', ['status'], unique=False)
    op.create_index(op.f('ix_recovery_cases_store_id'), 'recovery_cases', ['store_id'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('sold_on', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_promotion', sa.Boolean(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_sales_quantity_positive'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_product_id'), 'sales', ['product_id'], unique=False)
    op.create_index('ix_sales_product_store_date', 'sales', ['product_id', 'store_id', 'sold_on'], unique=False)
    op.create_index(op.f('ix_sales_sold_on'), 'sales', ['sold_on'], unique=False)
    op.create_index(op.f('ix_sales_store_id'), 'sales', ['store_id'], unique=False)
    op.create_table('agent_results',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('agent', sa.String(length=32), nullable=False),
    sa.Column('feasible', sa.Boolean(), nullable=False),
    sa.Column('reason_unavailable', sa.Text(), nullable=True),
    sa.Column('expected_units_cleared', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('expected_recovery', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('expected_loss', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('action_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('expected_net_recovery', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['recovery_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_results_agent'), 'agent_results', ['agent'], unique=False)
    op.create_index('ix_agent_results_case_agent', 'agent_results', ['case_id', 'agent'], unique=False)
    op.create_index(op.f('ix_agent_results_case_id'), 'agent_results', ['case_id'], unique=False)
    op.create_table('recovery_plans',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('strategy', sa.String(length=16), nullable=False),
    sa.Column('allocations', sa.JSON(), nullable=False),
    sa.Column('expected_recovery', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('expected_loss', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_action_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('expected_net_recovery', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('guardrail_status', sa.String(length=16), nullable=False),
    sa.Column('guardrail_findings', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['recovery_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_plans_case_id'), 'recovery_plans', ['case_id'], unique=False)
    op.create_index(op.f('ix_recovery_plans_status'), 'recovery_plans', ['status'], unique=False)
    op.create_table('actions',
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('agent', sa.String(length=32), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_summary', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('units >= 0', name='ck_actions_units_non_negative'),
    sa.ForeignKeyConstraint(['case_id'], ['recovery_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['recovery_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_actions_case_id'), 'actions', ['case_id'], unique=False)
    op.create_index(op.f('ix_actions_plan_id'), 'actions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_actions_status'), 'actions', ['status'], unique=False)
    op.create_table('verification_results',
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('predicted_units', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('simulated_units', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('predicted_recovery', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('simulated_recovery', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('units_variance_pct', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('recovery_variance_pct', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=False),
    sa.Column('simulated_window', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['recovery_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_results_plan_id'), 'verification_results', ['plan_id'], unique=False)
    op.create_table('action_results',
    sa.Column('action_id', sa.Uuid(), nullable=False),
    sa.Column('predicted_units', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('simulated_units', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('predicted_recovery', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('simulated_recovery', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('variance_pct', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_results_action_id'), 'action_results', ['action_id'], unique=False)
    op.create_table('b2b_orders',
    sa.Column('buyer_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by_action_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_orders_quantity_positive'),
    sa.ForeignKeyConstraint(['buyer_id'], ['b2b_buyers.id'], ),
    sa.ForeignKeyConstraint(['created_by_action_id'], ['actions.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_b2b_orders_buyer_id'), 'b2b_orders', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_b2b_orders_product_id'), 'b2b_orders', ['product_id'], unique=False)
    op.create_index(op.f('ix_b2b_orders_status'), 'b2b_orders', ['status'], unique=False)
    op.create_index(op.f('ix_b2b_orders_store_id'), 'b2b_orders', ['store_id'], unique=False)
    op.create_table('promotions',
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('anchor_product_id', sa.Uuid(), nullable=True),
    sa.Column('store_id', sa.Uuid(), nullable=True),
    sa.Column('discount_pct', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('incentive', sa.String(length=16), nullable=False),
    sa.Column('bundle_type', sa.String(length=32), nullable=True),
    sa.Column('starts_on', sa.Date(), nullable=True),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('created_by_action_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['anchor_product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['created_by_action_id'], ['actions.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotions_product_id'), 'promotions', ['product_id'], unique=False)
    op.create_table('store_transfers',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('source_store_id', sa.Uuid(), nullable=False),
    sa.Column('destination_store_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('transfer_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by_action_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_transfer_quantity_positive'),
    sa.CheckConstraint('source_store_id <> destination_store_id', name='ck_transfer_distinct_stores'),
    sa.ForeignKeyConstraint(['created_by_action_id'], ['actions.id'], ),
    sa.ForeignKeyConstraint(['destination_store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['source_store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_transfers_destination_store_id'), 'store_transfers', ['destination_store_id'], unique=False)
    op.create_index(op.f('ix_store_transfers_product_id'), 'store_transfers', ['product_id'], unique=False)
    op.create_index(op.f('ix_store_transfers_source_store_id'), 'store_transfers', ['source_store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_store_transfers_source_store_id'), table_name='store_transfers')
    op.drop_index(op.f('ix_store_transfers_product_id'), table_name='store_transfers')
    op.drop_index(op.f('ix_store_transfers_destination_store_id'), table_name='store_transfers')
    op.drop_table('store_transfers')
    op.drop_index(op.f('ix_promotions_product_id'), table_name='promotions')
    op.drop_table('promotions')
    op.drop_index(op.f('ix_b2b_orders_store_id'), table_name='b2b_orders')
    op.drop_index(op.f('ix_b2b_orders_status'), table_name='b2b_orders')
    op.drop_index(op.f('ix_b2b_orders_product_id'), table_name='b2b_orders')
    op.drop_index(op.f('ix_b2b_orders_buyer_id'), table_name='b2b_orders')
    op.drop_table('b2b_orders')
    op.drop_index(op.f('ix_action_results_action_id'), table_name='action_results')
    op.drop_table('action_results')
    op.drop_index(op.f('ix_verification_results_plan_id'), table_name='verification_results')
    op.drop_table('verification_results')
    op.drop_index(op.f('ix_actions_status'), table_name='actions')
    op.drop_index(op.f('ix_actions_plan_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_case_id'), table_name='actions')
    op.drop_table('actions')
    op.drop_index(op.f('ix_recovery_plans_status'), table_name='recovery_plans')
    op.drop_index(op.f('ix_recovery_plans_case_id'), table_name='recovery_plans')
    op.drop_table('recovery_plans')
    op.drop_index(op.f('ix_agent_results_case_id'), table_name='agent_results')
    op.drop_index('ix_agent_results_case_agent', table_name='agent_results')
    op.drop_index(op.f('ix_agent_results_agent'), table_name='agent_results')
    op.drop_table('agent_results')
    op.drop_index(op.f('ix_sales_store_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_sold_on'), table_name='sales')
    op.drop_index('ix_sales_product_store_date', table_name='sales')
    op.drop_index(op.f('ix_sales_product_id'), table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_recovery_cases_store_id'), table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_status'), table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_risk_band'), table_name='recovery_cases')
    op.drop_index('ix_recovery_cases_product_store', table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_product_id'), table_name='recovery_cases')
    op.drop_table('recovery_cases')
    op.drop_index(op.f('ix_inventory_store_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_product_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_last_sold_at'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_forecasts_store_id'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_product_id'), table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_stores_code'), table_name='stores')
    op.drop_table('stores')
    op.drop_table('settings')
    op.drop_table('categories')
    op.drop_index(op.f('ix_b2b_buyers_business_name'), table_name='b2b_buyers')
    op.drop_table('b2b_buyers')
    op.drop_index(op.f('ix_audit_logs_sku'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_occurred_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
